<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Message</code>
 */
class Message extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_code = 1;</code>
     */
    private $user_code = '';
    /**
     * Generated from protobuf field <code>string user_name = 2;</code>
     */
    private $user_name = '';
    /**
     * Generated from protobuf field <code>string content = 3;</code>
     */
    private $content = '';
    /**
     * Generated from protobuf field <code>string to_user = 4;</code>
     */
    private $to_user = '';

    public function __construct() {
        \GPBMetadata\Message::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string user_code = 1;</code>
     * @return string
     */
    public function getUserCode()
    {
        return $this->user_code;
    }

    /**
     * Generated from protobuf field <code>string user_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_name = 2;</code>
     * @return string
     */
    public function getUserName()
    {
        return $this->user_name;
    }

    /**
     * Generated from protobuf field <code>string user_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserName($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string content = 3;</code>
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>string content = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string to_user = 4;</code>
     * @return string
     */
    public function getToUser()
    {
        return $this->to_user;
    }

    /**
     * Generated from protobuf field <code>string to_user = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setToUser($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_user = $var;

        return $this;
    }

}

