<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace GPBMetadata;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a98010a0d6d6573736167652e70726f746f22510a074d65737361676512" .
            "110a09757365725f636f646518012001280912110a09757365725f6e616d" .
            "65180220012809120f0a07636f6e74656e74180320012809120f0a07746f" .
            "5f75736572180420012809222c0a0f4d657373616765526573706f6e7365" .
            "120c0a04636f6465180120012805120b0a036d7367180220012809620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

