<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace GPBMetadata;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6a0a0d6d6573736167652e70726f746f22510a074d6573736167651211" .
            "0a09757365725f636f646518012001280912110a09757365725f6e616d65" .
            "180220012809120f0a07636f6e74656e74180320012809120f0a07746f5f" .
            "75736572180420012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

