<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

namespace GPBMetadata;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a3e0a0d726571756573742e70726f746f22250a0752657175657374120c" .
            "0a0470617468180120012809120c0a04626f647918022001280c62067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

