<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

namespace GPBMetadata;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a400a0e726573706f6e73652e70726f746f22260a08526573706f6e7365" .
            "120c0a0470617468180120012809120c0a04626f647918022001280c6206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

