<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

namespace GPBMetadata;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4f0a0e726573706f6e73652e70726f746f22350a08526573706f6e7365" .
            "120c0a04636f6465180120012805120c0a0464617461180220012809120d" .
            "0a056578747261180320012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

